repos:

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        log_file: .pre-commit.log

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        log_file: .pre-commit.log

      - id: end-of-file-fixer
        log_file: .pre-commit.log

      - id: trailing-whitespace
        log_file: .pre-commit.log

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        log_file: .pre-commit.log

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        log_file: .pre-commit.log

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        log_file: .pre-commit.log

  - repo: local
    hooks:
      - id: test
        name: test-pydisplayinfo
        description: "Run test cases if previous hooks passed"
        files: "^(pydisplayinfo/|tests/).*$"
        entry: bash -c "if [ -f '.pre-commit.log' ]; then echo 'Solve previous hooks'; exit 1; else make test; fi"
        language: system
        pass_filenames: false
        verbose: True

  - repo: local
    hooks:
      - id: clean-log
        name: clean-log
        description: "Clean pre-commit log file"
        entry: rm -f ".pre-commit.log"
        language: system
        pass_filenames: false
        always_run: true
